Had to redo how crazy enchants were being initialized.  Need to get everything in the try catch for overall safety, but had to add NoClassDefFoundError too. This prevents this from failing when CE is not installed, but hwne it is, it allows the player to pickup the pickaxe enchantment experience bonus.